import { Mention, CrisisAlert, BrandOverview, SocialChannel, SentimentType, RiskLevel } from '../types/monitor';

export const INITIAL_BRAND: BrandOverview = {
  brandName: 'Sentinela Brand Tech',
  reputationScore: 84,
  totalMentions: 14280,
  growthRate24h: 18.5,
  sentimentSplit: {
    positive: 62,
    neutral: 24,
    negative: 11,
    critical: 3,
  },
  activeCrisisCount: 2,
  estimatedReach: 2850000,
};

export const INITIAL_ALERTS: CrisisAlert[] = [
  {
    id: 'alt-001',
    title: 'Pico de Menções Negativas no TikTok (Reclamação de Instabilidade)',
    description: 'Vídeo de influenciador com 450k seguidores viralizou reclamando de falha no login durante promoção relâmpago.',
    severity: 'critical',
    channel: 'tiktok',
    mentionCount: 840,
    negativeRatio: 78,
    triggeredAt: 'Há 18 minutos',
    status: 'active',
    recommendedAction: 'Publicar comunicado no perfil oficial e notificar equipe de DevOps sobre o gargalo no cluster de autenticação.',
    affectedTopics: ['#BugApp', 'LoginFalhou', 'Instabilidade', 'BlackFriday'],
  },
  {
    id: 'alt-002',
    title: 'Aumento de menções sensíveis no X (Twitter) sobre Atendimento',
    description: 'Aumento de 42% no volume de tweets citando termos como "Procon" e "demora no suporte".',
    severity: 'high',
    channel: 'twitter',
    mentionCount: 310,
    negativeRatio: 64,
    triggeredAt: 'Há 1 hora',
    status: 'investigating',
    recommendedAction: 'Reforçar equipe de primeiro nível no chat e disparar respostas automáticas para triagem prioritária.',
    affectedTopics: ['Procon', 'Suporte', 'Demora', 'ReclameAqui'],
  },
  {
    id: 'alt-003',
    title: 'Detecção de Fake News em Comunidade no Reddit',
    description: 'Postagem em fórum financeiro alegando vazamento inverídico de dados cadastrais.',
    severity: 'medium',
    channel: 'reddit',
    mentionCount: 95,
    negativeRatio: 45,
    triggeredAt: 'Há 3 horas',
    status: 'investigating',
    recommendedAction: 'Acionar assessoria jurídica e emitir nota de esclarecimento técnico via assessoria de imprensa.',
    affectedTopics: ['Segurança', 'Vazamento', 'Privacidade'],
  }
];

export const INITIAL_MENTIONS: Mention[] = [
  {
    id: 'men-001',
    channel: 'tiktok',
    author: {
      name: 'Gabriel Tech Reviews',
      username: '@gabrieltech',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      verified: true,
      followersCount: 480000,
    },
    content: 'Galera, tentei entrar no app para aproveitar a oferta especial e travou geral! Alguém mais com erro 504 no checkout? Não consigo finalizar compra! 😡💥',
    mediaType: 'video',
    mediaUrl: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&auto=format&fit=crop&q=80',
    transcription: '[Áudio Transcrito por IA]: "...olha aqui na tela, fica carregando em loop e fecha o app sozinho. Espero que resolvam logo..."',
    timestamp: 'Há 12 min',
    likes: 4200,
    comments: 630,
    shares: 180,
    sentiment: 'critical',
    sentimentScore: 0.94,
    riskLevel: 'critical',
    topics: ['#BugApp', 'LoginFalhou', 'Instabilidade'],
    reachEstimate: 350000,
    aiAnalysis: {
      summary: 'Reclamação viral em vídeo sobre falha no checkout gerando alta taxa de concordância nos comentários.',
      emotion: 'Indignação',
      crisisIndicator: true,
      suggestedAction: 'Prioridade máxima: Contatar o criador com solução técnica e cupom de retratação.',
    }
  },
  {
    id: 'men-002',
    channel: 'instagram',
    author: {
      name: 'Camila Ferreira',
      username: '@camilastyle',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      verified: true,
      followersCount: 125000,
    },
    content: 'Apaixonada na nova atualização do Sentinela! O painel de inteligência de dados facilitou demais minha rotina de relatórios. Parabéns aos desenvolvedores! ✨💜🚀',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
    timestamp: 'Há 25 min',
    likes: 2890,
    comments: 112,
    shares: 45,
    sentiment: 'positive',
    sentimentScore: 0.98,
    riskLevel: 'low',
    topics: ['#Inovação', 'UXDesign', 'Produtividade', 'Tecnologia'],
    reachEstimate: 98000,
    aiAnalysis: {
      summary: 'Elogio orgânico espontâneo de micro-influenciadora com alta autoridade de nicho.',
      emotion: 'Alegria / Entusiasmo',
      crisisIndicator: false,
      suggestedAction: 'Repostar nos Stories oficiais e engajar com agradecimento personalizado.',
    }
  },
  {
    id: 'men-003',
    channel: 'twitter',
    author: {
      name: 'Rodrigo M. Costa',
      username: '@rodrigomcosta',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
      verified: false,
      followersCount: 3400,
    },
    content: 'Já é a terceira vez que tento falar com o atendimento pelo chat e o bot fica em looping infinito. Se não responderem até o fim do dia vou abrir reclamação no Procon! @SentinelaTech',
    timestamp: 'Há 45 min',
    likes: 48,
    comments: 19,
    shares: 12,
    sentiment: 'negative',
    sentimentScore: 0.82,
    riskLevel: 'high',
    topics: ['Procon', 'Suporte', 'Demora'],
    reachEstimate: 14500,
    aiAnalysis: {
      summary: 'Ameaça de acionamento de órgão de defesa do consumidor (Procon) devido a falha na triagem do chatbot.',
      emotion: 'Frustração',
      crisisIndicator: true,
      suggestedAction: 'Transferir atendimento imediatamente para operador humano sênior.',
    }
  },
  {
    id: 'men-004',
    channel: 'news',
    author: {
      name: 'Portal Mundo Digital',
      username: 'mundodigital.com.br',
      avatar: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=150&auto=format&fit=crop&q=80',
      verified: true,
      followersCount: 920000,
    },
    content: 'Sentinela lança novo motor de inteligência artificial preditiva para monitoramento e prevenção de crises corporativas na América Latina.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&auto=format&fit=crop&q=80',
    timestamp: 'Há 2 horas',
    likes: 1200,
    comments: 85,
    shares: 340,
    sentiment: 'positive',
    sentimentScore: 0.92,
    riskLevel: 'low',
    topics: ['#IA', 'Inovação', 'MercadoTech', 'Lançamento'],
    reachEstimate: 420000,
    aiAnalysis: {
      summary: 'Matéria de imprensa positiva destacando liderança tecnológica e inovação no mercado B2B.',
      emotion: 'Reconhecimento',
      crisisIndicator: false,
      suggestedAction: 'Compartilhar no LinkedIn institucional e na página de imprensa.',
    }
  },
  {
    id: 'men-005',
    channel: 'youtube',
    author: {
      name: 'Canal Growth & Mídia',
      username: '@growthmidia',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      verified: true,
      followersCount: 290000,
    },
    content: 'Vídeo novo no ar: "Testei as 5 melhores ferramentas de Social Listening do mercado em 2026". Veja os pontos fortes e fracos de cada uma!',
    mediaType: 'video',
    mediaUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    transcription: '[Áudio Transcrito por IA]: "...a velocidade de processamento de alertas e a precisão do sentimento da Sentinela foi de longe a mais impressionante no teste prático..."',
    timestamp: 'Há 3 horas',
    likes: 3100,
    comments: 240,
    shares: 190,
    sentiment: 'positive',
    sentimentScore: 0.89,
    riskLevel: 'low',
    topics: ['#Review', 'SocialListening', 'Benchmark', 'Ferramentas'],
    reachEstimate: 210000,
    aiAnalysis: {
      summary: 'Review comparativo altamente favorável em canal especializado de marketing e tecnologia.',
      emotion: 'Aprovação',
      crisisIndicator: false,
      suggestedAction: 'Fixar comentário oficial no vídeo com cupom para inscritos.',
    }
  }
];

export const TOPICS_DATA = [
  { name: 'Sentinela.ai', count: 5420, sentiment: 'positive', growth: '+24%' },
  { name: '#BugApp', count: 1890, sentiment: 'critical', growth: '+140%' },
  { name: 'IA Preditiva', count: 1650, sentiment: 'positive', growth: '+35%' },
  { name: 'Suporte & Chat', count: 1120, sentiment: 'negative', growth: '+12%' },
  { name: 'Atualização V2', count: 980, sentiment: 'positive', growth: '+45%' },
  { name: 'Procon', count: 410, sentiment: 'critical', growth: '+85%' },
  { name: '#InovaçãoTech', count: 820, sentiment: 'positive', growth: '+18%' },
];

export const VOLUME_TIMELINE_DATA = [
  { time: '00:00', volume: 140, positive: 90, negative: 20, critical: 2 },
  { time: '03:00', volume: 80, positive: 50, negative: 12, critical: 1 },
  { time: '06:00', volume: 290, positive: 180, negative: 40, critical: 5 },
  { time: '09:00', volume: 890, positive: 560, negative: 120, critical: 15 },
  { time: '12:00', volume: 1420, positive: 880, negative: 210, critical: 32 },
  { time: '14:00', volume: 2100, positive: 1120, negative: 450, critical: 84 }, // Pico da crise
  { time: '16:00', volume: 1750, positive: 1040, negative: 320, critical: 45 },
  { time: '18:00', volume: 1320, positive: 890, negative: 190, critical: 20 },
];
